[versions]
netty = "4.1.115.Final"
mdcfg = "2.5.1"
mdlib = "1.8.0-SNAPSHOT"
smi = "0.1.0"
slf4j = "2.0.11"
jbr-anno = "24.1.0"
zstd = "1.5.5-5"

[libraries]
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
midnight-cfg = { module = "org.wallentines:midnightcfg-api", version.ref="mdcfg" }
midnight-cfg-sql = { module = "org.wallentines:midnightcfg-api-sql", version.ref="mdcfg" }
midnight-cfg-json = { module = "org.wallentines:midnightcfg-codec-json", version.ref="mdcfg" }
midnight-cfg-gson = { module = "org.wallentines:midnightcfg-codec-gson", version.ref="mdcfg" }
midnight-cfg-binary = { module = "org.wallentines:midnightcfg-codec-binary", version.ref="mdcfg" }
midnight-cfg-nbt = { module = "org.wallentines:midnightcfg-codec-nbt", version.ref="mdcfg" }
midnight-lib = { module = "org.wallentines:midnightlib", version.ref="mdlib" }
smi-api = { module = "org.wallentines:smi-api", version.ref = "smi" }
smi-base = { module = "org.wallentines:smi-base", version.ref = "smi" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref="jbr-anno" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }
